baseURL = "https://michaelgallo.dev/"
title = "Michael Gallo"
enableRobotsTXT = false
disableKinds = ["taxonomy", "term"]
summaryLength = 100000

[params]
  description = "Michael Gallo is a senior software engineer specializing in Go, Python, Linux, AWS, and scalable backend systems."

[permalinks]
  blog = "/blog/:slugorcontentbasename"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]
  page = ["HTML"]
