service: portfolio_website

image: michaelagallo95/portfolio-website

servers:
  web:
    - <%= ENV.fetch("KAMAL_HOST", "your-server-ip") %>

proxy:
  ssl: true
  host: michaelgallo.dev

registry:
  server: registry.gitlab.com
  username: <%= ENV.fetch("KAMAL_REGISTRY_USERNAME", "gitlab-ci-token") %>
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    RAILS_LOG_LEVEL: info
    WEB_CONCURRENCY: auto

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f

asset_path: /rails/public/assets

builder:
  arch: amd64

ssh:
  user: <%= ENV.fetch("KAMAL_SSH_USER", "root") %>
